name: qabsolaa
description: "A Flutter application for managing student attendance using QR codes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8

  uuid: ^4.3.3
  intl: ^0.19.0

  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  file_picker: ^10.2.0
  excel: ^4.0.6
  collection: ^1.19.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  audioplayers: ^6.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/123.png"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
assets:
  - assets/sounds/
  - lib/assets/
  - assets/fonts/arial.ttf
  - assets/0.png