// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHv9J7IsZHvfbH3q5scG1rOr5qRuiblQ4',
    appId: '1:984494773799:web:34cb9ffbdf2bc8308f2002',
    messagingSenderId: '984494773799',
    projectId: 'qabsola-68c64',
    authDomain: 'qabsola-68c64.firebaseapp.com',
    storageBucket: 'qabsola-68c64.firebasestorage.app',
    measurementId: 'G-D8TC5LVTT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK8C2YMnOxaBtW4jh0PQa8cJnldUssQ2E',
    appId: '1:984494773799:android:fbcb413cc763a8ad8f2002',
    messagingSenderId: '984494773799',
    projectId: 'qabsola-68c64',
    storageBucket: 'qabsola-68c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq5Mqa4H-rDpZi18HCIP2-VDLZeTfEFwo',
    appId: '1:984494773799:ios:68b6ae60f342170c8f2002',
    messagingSenderId: '984494773799',
    projectId: 'qabsola-68c64',
    storageBucket: 'qabsola-68c64.firebasestorage.app',
    iosBundleId: 'com.example.qabsolaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq5Mqa4H-rDpZi18HCIP2-VDLZeTfEFwo',
    appId: '1:984494773799:ios:68b6ae60f342170c8f2002',
    messagingSenderId: '984494773799',
    projectId: 'qabsola-68c64',
    storageBucket: 'qabsola-68c64.firebasestorage.app',
    iosBundleId: 'com.example.qabsolaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHv9J7IsZHvfbH3q5scG1rOr5qRuiblQ4',
    appId: '1:984494773799:web:49ee745c7b1d82f18f2002',
    messagingSenderId: '984494773799',
    projectId: 'qabsola-68c64',
    authDomain: 'qabsola-68c64.firebaseapp.com',
    storageBucket: 'qabsola-68c64.firebasestorage.app',
    measurementId: 'G-2EDRYFBRLR',
  );

}